{
 "title": "Spring Boot - Validación Activa",
 "refresh": "10s",
 "panels": [
  {
   "title": "Total de Llamadas HTTP",
   "type": "stat",
   "gridPos": { "x": 0, "y": 0, "w": 6, "h": 6 },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count[5m]))"
    }
   ]
  },
  {
   "title": "Llamadas por Endpoint",
   "type": "table",
   "gridPos": { "x": 6, "y": 0, "w": 18, "h": 8 },
   "targets": [
    {
     "expr": "sum by (uri, method) (rate(http_server_requests_seconds_count[1m]))"
    }
   ]
  },
  {
   "title": "Tiempo Promedio por Request (último minuto)",
   "type": "stat",
   "gridPos": { "x": 0, "y": 6, "w": 12, "h": 6 },
   "format": "s",
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_sum[1m]) / rate(http_server_requests_seconds_count[1m])"
    }
   ]
  },
  {
   "title": "Porcentaje de Errores (últimos 5m)",
   "type": "stat",
   "gridPos": { "x": 12, "y": 6, "w": 12, "h": 6 },
   "format": "percentunit",
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{status!~\"2..\"}[5m])) / sum(rate(http_server_requests_seconds_count[5m])) * 100"
    }
   ]
  }
 ]
}